name: example
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:

  flutter:
    sdk: flutter
  supabase_auth_ui: ^0.4.2
  sms_autofill: ^2.2.0

  supabase_flutter: ^2.3.2
  marquee: ^2.0.3
  #supabase_flutter: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  #flutter_launcher_icons: ^0.13.1

    #flutter_icons:
    # android: "launcher icon"
    #ios: true
  #image_path: "images/contact.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logos/
    - images/
